version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: msg-demo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: msgpass
      MYSQL_DATABASE: msg_demo
      TZ: Asia/Shanghai
    ports:
      - '3308:3306'
    volumes:
      - ./backend/inbox/db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./mysql-data:/var/lib/mysql
    command: [
      "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--default-time-zone=+08:00"
    ]

